# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# see also: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll

header_title: Music Scores
subtitle: Sheet music for classical guitar.
title: Music Scores \| Classical guitar sheet music PDF editions from Jonty Dawson.

baseurl: "/music-scores" # the subpath of your site, e.g. /blog
url: "https://jonty-dawson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
copyright: Copyright © 2022-2024 Jonty Dawson
edition_preview_suffix: .preview.png
edition_card_suffix: .card.jpg
edition_download_dir: assets/downloads
edition_preview_dir: assets/preview-images
edition_card_dir: assets/edition-cards
excerpt_separator: <!--more-->

# Build settings
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-sitemap

header_anchors:
  - { id: "editions", title: "Editions" }
  - { id: "about", title: "About" }
# header_pages:
#  - about.md

collections:
  editions:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: "editions"
    values:
      seo:
        type: Article
      preview_caption: ""
      arranger: Jonty Dawson
      image:
        path: assets/edition-cards/default-1200x628.card.jpg
        width: 1200
        height: 628
  -
    scope:
      path: "assets/downloads/*.pdf"
    values:
      sitemap: false

recent_edition_date: 2024-12-01
recent_edition_tagline: "✨NEW✨ · "


minima:
  skin: classic

  social_links:
    - { platform: twitter, user_url: "https://twitter.com/JontyDawson" }
    - { platform: github, user_url: "https://github.com/jonty-dawson" }

# jekyll-seo-tag
author:
  name: Jonty Dawson
  twitter: JontyDawson
  url: https://github.com/jonty-dawson

social:
  name: Jonty Dawson
  links:
    - https://twitter.com/JontyDawson
    - https://github.com/jonty-dawson
    - http://www.linkedin.com/in/jontydawson

logo: /favicon.svg

# used for twitter card twitter:site
twitter:
  username: JontyDawson

goatcounter_analytics:
  code: jonty-dawson-github
  allow_local: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
